Script started on 2023-02-05 15:38:03-08:00 [TERM="xterm-256color" TTY="/dev/pts/6" COLUMNS="125" LINES="39"]
[1m[38;5;118m[7m%[27m[1m[38;5;118m[0m[38;5;118m                                                                                                                             ]2;ssusanto@DESKTOP-KR0Q71I:~/CS353/Lab3/lab3data]1;..Lab3/lab3data[0m[27m[24m[J[38;5;135mssusanto[00m in [38;5;118m~/CS353/Lab3/lab3data[00m on [38;5;81mmaster[38;5;161m ●[00m[38;5;166m λ[00m [K[?1h=[?2004h[32mg[39m[32mg[39m[90mdb echo-server[39m[14D[32mg[32md[39m[32mg[32md[32mb[39m[39m [39m[4me[39m[4mc[39m[4mh[39m[4mo[39m[4m-[39m[4ms[39m[4me[39m[4mr[39m[4mv[39m[4me[39m[4mr[24m[?1l>[?2004l
]2;gdb echo-server]1;gdb[35;1m[35;1mGNU gdb [m[35;1m(Ubuntu 9.2-0ubuntu1~20.04.1) [m[35;1m9.2[m[35;1m
[m[mCopyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from [32mecho-server[m...
(gdb) list 76
71	    if (gnDebug) {
72	        cerr << "[DBG-SVR] " << dec << bytes_received << " bytes received from " << get_ip_and_port_for_server(newsockfd, 0) << " (data displayed in next line, <TAB>-indented):\n\t";
73	        write(2, buf, bytes_received);
74	        if (!(bytes_received > 0 && buf[bytes_received-1] == '\n')) cerr << endl;
75	        if (bytes_received > 0) {
76	            cerr << "\t";
77	            for (int i=0; i < bytes_received; i++) {
78	                cerr << "0x" << setfill('0') << setw(2) << hex << (int)buf[i] << " ";
79	            }
80	            cerr << endl;
(gdb) break 76
Breakpoint 1 at [34m0x295b[m: file [32mecho-server.cpp[m, line 76.
(gdb) break main
Breakpoint 2 at [34m0x2aac[m: file [32mecho-server.cpp[m, line 90.
(gdb) run ./echo-server 12345
Starting program: /home/ssusanto/CS353/Lab3/lab3data/echo-server ./echo-server 12345

Breakpoint 2, [33mmain[m ([36margc[m=1, [36margv[m=0x280) at [32mecho-server.cpp[m:90
90	{
(gdb) list
85	    shutdown(newsockfd, SHUT_RDWR);
86	    close(newsockfd);
87	}
88	
89	int main(int argc, char *argv[])
90	{
91	    process_options(argc, argv);
92	    listen_socket_fd = create_listening_socket(argv[1]);
93	    if (listen_socket_fd != (-1)) {
94	        if (gnDebug) {
(gdb) print argc
$1 = 1
(gdb) print argv[0]
Cannot access memory at address 0x280
(gdb) print[K[K[K[K[KQuit
(gdb) Quit
Undefined command: "Quit".  Try "help".
(gdb) Quit
(gdb) quit
A debugging session is active.

	Inferior 1 [process 14651] will be killed.

Quit anyway? (y or n) y
[1m[7m%[27m[1m[0m                                                                                                                             ]2;ssusanto@DESKTOP-KR0Q71I:~/CS353/Lab3/lab3data]1;..Lab3/lab3data[0m[27m[24m[J[38;5;135mssusanto[00m in [38;5;118m~/CS353/Lab3/lab3data[00m on [38;5;81mmaster[38;5;161m ●[00m[38;5;166m λ[00m [K[?1h=[?2004h[1m[31mc[0m[39m[0m[32mc[32md[39m[90m CS353/Lab3/lab3data[39m[20D[39m [39m[4m.[24m[39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [18D[90m./Lab3[39m[4m.[39m[4m.[24m[39m [39m [39m [39m [39m [?1l>[?2004l
]2;cd ..]1;cd[1m[7m%[27m[1m[0m                                                                                                                        