Script started on 2023-02-05 15:27:28-08:00 [TERM="xterm-256color" TTY="/dev/pts/1" COLUMNS="120" LINES="30"]
[1m[38;5;118m[7m%[27m[1m[38;5;118m[0m[38;5;118m                                                                                                                        ]2;ssusanto@DESKTOP-KR0Q71I:~/CS353/Lab3/lab3data]1;..Lab3/lab3data[0m[27m[24m[J[38;5;135mssusanto[00m in [38;5;118m~/CS353/Lab3/lab3data[00m on [38;5;81mmaster[38;5;161m ●[00m[38;5;166m λ[00m [K[?1h=[?2004h[1m[31mu[0m[39m[1m[31mu[0m[39m[90mname -a[39m[1m[31mu[1m[31mn[0m[39m[90mn[90ma[90mm[90me[90m [90m-[90ma[39m[1m[31mu[1m[31mn[1m[31ma[0m[39m[90mn[90ma[90mm[90me[90m [90m-[90ma[39m[1m[31ma[1m[31mm[0m[39m[90mn[90ma[90mm[90me[90m [90m-[90ma[39m[0m[32mu[0m[32mn[0m[32ma[0m[32mm[32me[39m[39m [39m [39m [39m [39m [39m  [90m-a[39m[39m-[39ma[?1l>[?2004l
]2;uname -a]1;unameLinux DESKTOP-KR0Q71I 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
[1m[7m%[27m[1m[0m                                                                                                                        ]2;ssusanto@DESKTOP-KR0Q71I:~/CS353/Lab3/lab3data]1;..Lab3/lab3data[0m[27m[24m[J[38;5;135mssusanto[00m in [38;5;118m~/CS353/Lab3/lab3data[00m on [38;5;81mmaster[38;5;161m ●[00m[38;5;166m λ[00m [K[?1h=[?2004h[1m[31mc[0m[39m[1m[31mc[1m[31ma[0m[39m[90mt /etc/os-release[39m[17D[0m[32mc[0m[32ma[32mt[39m[39m [39m[4m/[24m[4m/[39m[4me[24m[4me[39m[4mt[24m[4mt[39m[4mc[24m[4mc[39m[4m/[24m[4m/[39m[4mo[39m[4ms[39m[4m-[39m[4mr[39m[4me[39m[4ml[39m[4me[39m[4ma[39m[4ms[39m[4me[24m[?1l>[?2004l
]2;cat /etc/os-release]1;catNAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
[1m[7m%[27m[1m[0m                                                                                                                        ]2;ssusanto@DESKTOP-KR0Q71I:~/CS353/Lab3/lab3data]1;..Lab3/lab3data[0m[27m[24m[J[38;5;135mssusanto[00m in [38;5;118m~/CS353/Lab3/lab3data[00m on [38;5;81mmaster[38;5;161m ●[00m[38;5;166m λ[00m [K[?1h=[?2004h[1m[31mm[0m[39m[0m[39mma[1m[31mm[1m[31ma[1m[31mk[0m[39m[0m[32mm[0m[32ma[0m[32mk[32me[39m[90m qemu-nox[39m[9D[39m [39m[4me[24m[39m [39m [39m [39m [39m [39m [39m [90mxec[39m[4me[39m[4mc[24m[39m [39m [4mc[4mh[24m[4mh[4mo[24m[4mo[4m-[24m[4m-[4ms[24m[4ms[4me[24m[4me[4mr[24m[4mr[4mv[24m[4mv[4me[24m[4me[4mr[24m[?1l>[?2004l[11D[24me[24mc[24mh[24mo[24m-[24ms[24me[24mr[24mv[24me[24mr
]2;make echo-server]1;makeg++ -g -Wall -std=c++11 -DLOCALHOST=\"127.0.0.1\" -o echo-server echo-server.cpp my_socket.cpp
[1m[7m%[27m[1m[0m                                                                                                                        ]2;ssusanto@DESKTOP-KR0Q71I:~/CS353/Lab3/lab3data]1;..Lab3/lab3data[0m[27m[24m[J[38;5;135mssusanto[00m in [38;5;118m~/CS353/Lab3/lab3data[00m on [38;5;81mmaster[38;5;161m ●[00m[38;5;166m λ[00m [K[?1h=[?2004h[1m[31mm[0m[39m[1m[31mm[1m[31ma[0m[39m[1m[31mm[1m[31ma[1m[31mk[0m[39m[0m[39mm[0m[39ma[0m[39mke[32mm[32ma[32mk[32me[39m [90mecho-server[39m[11D[39m[4me[24m[4me[39m[4mc[24m[4mc[39m[4mh[24m[4mh[39m[4mo[24m[4mo[39m[4m-[24m[4m-[39m[4mc[24m[39m [39m [39m [39m [39m [4mc[4ml[24m[4ml[4mi[24m[4mi[4me[24m[4me[4mn[24m[4mn[4mt[24m[?1l>[?2004l[11D[24me[24mc[24mh[24mo[24m-[24mc[24ml[24mi[24me[24mn[24mt
]2;make echo-client]1;makeg++ -g -Wall -std=c++11 -DLOCALHOST=\"127.0.0.1\" -o echo-client echo-client.cpp my_socket.cpp
[1m[7m%[27m[1m[0m                                                                                                                        ]2;ssusanto@DESKTOP-KR0Q71I:~/CS353/Lab3/lab3data]1;..Lab3/lab3data[0m[27m[24m[J[38;5;135mssusanto[00m in [38;5;118m~/CS353/Lab3/lab3data[00m on [38;5;81mmaster[38;5;161m ●[00m[38;5;166m λ[00m [K[?1h=[?2004h[32m.[39m[32m.[39m[90m/section-A.csh[39m[14D[4m[32m.[4m[32m/[24m[39m[39m[4m.[39m[4m/[39m[4me[24m[39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [12D[90mxample[39m[4me[39m[4mc[24m[39m [39m [39m [39m [39m [4mc[4mh[24m[4mh[4mo[24m[4mo[4m-[24m[4m-[4ms[24m[4ms[4me[24m[4me[4mr[24m[4mr[4mv[24m[4mv[4me[24m[12D[24m[32m.[24m[32m/[24m[32me[24m[32mc[24m[32mh[24m[32mo[24m[32m-[24m[32ms[24m[32me[24m[32mr[24m[32mv[24m[32me[32mr[39m 12345[?1l>[?2004l
]2;./echo-server 12345]1;./echo-server[DBG-SVR]	argv[0]: './echo-server'
[DBG-SVR]	argv[1]: '12345'
[SERVER]	listening at 127.0.0.1:12345
[DBG-SVR] 13 bytes received from 127.0.0.1:45098 (data displayed in next line, <TAB>-indented):
	Hello World!
	0x48 0x65 0x6c 0x6c 0x6f 0x20 0x57 0x6f 0x72 0x6c 0x64 0x21 0x0a 
[DBG-SVR] 18 bytes received from 127.0.0.1:45100 (data displayed in next line, <TAB>-indented):
	Good-bye for now.
	0x47 0x6f 0x6f 0x64 0x2d 0x62 0x79 0x65 0x20 0x66 0x6f 0x72 0x20 0x6e 0x6f 0x77 0x2e 0x0a 
[DBG-SVR] 0 bytes received from 127.0.0.1:45102 (data displayed in next line, <TAB>-indented):
	
^C
[1m[7m%[27m[1m[0m                                                                                                                        ]2;ssusanto@DESKTOP-KR0Q71I:~/CS353/Lab3/lab3data]1;..Lab3/lab3data[0m[27m[24m[J[38;5;135mssusanto[00m in [38;5;118m~/CS353/Lab3/lab3data[00m on [38;5;81mmaster[38;5;161m ●[00m[38;5;166m λ[00m [K[?1h=[?2004h[4me[24m[4me[24m[90mb[39m[24m[32me[32mx[39m[90mit[39m[1m[31me[1m[31mx[1m[31mi[0m[39m[90mi[90mt[39m[0m[32me[0m[32mx[0m[32mi[32mt[39m[39m [?1l>[?2004l
]2;exit]1;exit
Script done on 2023-02-05 15:29:28-08:00 [COMMAND_EXIT_CODE="130"]
