Script started on Sun 05 Feb 2023 03:54:23 PM PST
]0;ssusanto@CS350: ~/CS353/Lab3/lab3data[01;32mssusanto@CS350[00m:[01;34m~/CS353/Lab3/lab3data[00m$ ./echo-client 12345
echo-client at 127.0.0.1:40124 is connected to server at 127.0.0.1:12345
Enter a string to send to the echo server: Hello World!
13 bytes sent from 127.0.0.1:40124
13 bytes received, see next line for data...
Hello World!
]0;ssusanto@CS350: ~/CS353/Lab3/lab3data[01;32mssusanto@CS350[00m:[01;34m~/CS353/Lab3/lab3data[00m$ ./client[K[K[K[K[K[Kecho-client 12345
echo-client at 127.0.0.1:40126 is connected to server at 127.0.0.1:12345
Enter a string to send to the echo server: Good-bye for ow  now.
18 bytes sent from 127.0.0.1:40126
18 bytes received, see next line for data...
Good-bye for now.
]0;ssusanto@CS350: ~/CS353/Lab3/lab3data[01;32mssusanto@CS350[00m:[01;34m~/CS353/Lab3/lab3data[00m$ ./echo-client 12345exit[Kmake echo-serverexit[K./echo-client 12345[K./echo-client 12345
echo-client at 127.0.0.1:40128 is connected to server at 127.0.0.1:12345
Enter a string to send to the echo server: 
]0;ssusanto@CS350: ~/CS353/Lab3/lab3data[01;32mssusanto@CS350[00m:[01;34m~/CS353/Lab3/lab3data[00m$ exit
exit

Script done on Sun 05 Feb 2023 03:55:08 PM PST
