MYDEFS = -g -Wall -std=c++11 -DLOCALHOST=\"127.0.0.1\"

all: lab1b lab1c

lab1b: lab1b.cpp
	g++ ${MYDEFS} -o lab1b lab1b.cpp

lab1c: lab1c.cpp
	g++ ${MYDEFS} -o lab1c lab1c.cpp

clean:
	rm -f lab1b lab1c *.o
