Script started on 2023-02-06 21:22:05-08:00 [TERM="xterm-256color" TTY="/dev/pts/5" COLUMNS="125" LINES="39"]
[1m[38;5;118m[7m%[27m[1m[38;5;118m[0m[38;5;118m                                                                                                                             ]2;ssusanto@DESKTOP-KR0Q71I:~/CS353/Lab3/lab3data]1;..Lab3/lab3data[0m[27m[24m[J[38;5;135mssusanto[00m in [38;5;118m~/CS353/Lab3/lab3data[00m on [38;5;81mmaster[38;5;166m ●[38;5;161m ●[00m[38;5;166m λ[00m [K[?1h=[?2004h[32m.[39m[32m.[39m[90m/lab3c 12345[39m[12D[4m[32m.[4m[32m/[24m[39m[39m[4m.[39m[4m/[39m[4ml[24m[4ml[39m[4ma[24m[4ma[39m[4mb[24m[4mb[39m[4m3[24m[24m[32m.[24m[32m/[24m[32ml[24m[32ma[24m[32mb[24m[32m3[32mc[39m[39m [39m-[39m [39m [39m [39m [90mc 12345[39m[39mc[39m [39m1[39m2[39m3[39m4[39m5[?1l>[?2004l
]2;./lab3c -c 12345]1;./lab3c[DBG-SVR]	argv[0]: './lab3c'
[DBG-SVR]	argv[1]: '-c'
[DBG-SVR]	argv[2]: '12345'
echo-client at 127.0.0.1:45384 is connected to server at 127.0.0.1:12345
Enter a string to send to the echo server: Hello World!
13 bytes sent from 127.0.0.1:45384
13 bytes received, see next line for data...
Hello World!
[1m[7m%[27m[1m[0m                                                                                                                             ]2;ssusanto@DESKTOP-KR0Q71I:~/CS353/Lab3/lab3data]1;..Lab3/lab3data[0m[27m[24m[J[38;5;135mssusanto[00m in [38;5;118m~/CS353/Lab3/lab3data[00m on [38;5;81mmaster[38;5;166m ●[38;5;161m ●[00m[38;5;166m λ[00m [K[?1h=[?2004h[32m./lab3c[39m -c 12345[?1l>[?2004l
]2;./lab3c -c 12345]1;./lab3c[DBG-SVR]	argv[0]: './lab3c'
[DBG-SVR]	argv[1]: '-c'
[DBG-SVR]	argv[2]: '12345'
echo-client at 127.0.0.1:45386 is connected to server at 127.0.0.1:12345
Enter a string to send to the echo server: Good-bye for now.
18 bytes sent from 127.0.0.1:45386
18 bytes received, see next line for data...
Good-bye for now.
[1m[7m%[27m[1m[0m                                                                                                                             ]2;ssusanto@DESKTOP-KR0Q71I:~/CS353/Lab3/lab3data]1;..Lab3/lab3data[0m[27m[24m[J[38;5;135mssusanto[00m in [38;5;118m~/CS353/Lab3/lab3data[00m on [38;5;81mmaster[38;5;166m ●[38;5;161m ●[00m[38;5;166m λ[00m [K[?1h=[?2004h[32m./lab3c[39m -c 12345[?1l>[?2004l
]2;./lab3c -c 12345]1;./lab3c[DBG-SVR]	argv[0]: './lab3c'
[DBG-SVR]	argv[1]: '-c'
[DBG-SVR]	argv[2]: '12345'
echo-client at 127.0.0.1:45388 is connected to server at 127.0.0.1:12345
Enter a string to send to the echo server: 
[1m[7m%[27m[1m[0m                                                                                                                             ]2;ssusanto@DESKTOP-KR0Q71I:~/CS353/Lab3/lab3data]1;..Lab3/lab3data[0m[27m[24m[J[38;5;135mssusanto[00m in [38;5;118m~/CS353/Lab3/lab3data[00m on [38;5;81mmaster[38;5;166m ●[38;5;161m ●[00m[38;5;166m λ[00m [K[?1h=[?2004h[1m[31me[0m[39m[1m[31me[0m[39m[90mxit[39m[0m[32me[32mx[39m[1m[31me[1m[31mx[1m[31mi[0m[39m[0m[32me[0m[32mx[0m[32mi[32mt[39m[?1l>[?2004l
]2;exit]1;exit
Script done on 2023-02-06 21:22:30-08:00 [COMMAND_EXIT_CODE="0"]
