MYDEFS = -g -Wall -std=c++11 -DLOCALHOST=\"127.0.0.1\"

all: lab2a lab2b lab2c

lab2a: lab2a.cpp
	g++ ${MYDEFS} -o lab2a lab2a.cpp

lab2b: lab2b.cpp
	g++ ${MYDEFS} -o lab2b lab2b.cpp

lab2c: lab2c.cpp
	g++ ${MYDEFS} -o lab2c lab2c.cpp

clean:
	rm -f lab2a lab2b lab2c *.o