Script started on 2023-02-27 18:11:04-08:00 [TERM="xterm-256color" TTY="/dev/pts/1" COLUMNS="132" LINES="40"]
[1m[38;5;118m[7m%[27m[1m[38;5;118m[0m[38;5;118m                                                                                                                                    ]2;ssusanto@DESKTOP-KR0Q71I:~/CS353/Lab7]1;~/CS353/Lab7[0m[27m[24m[J[38;5;135mssusanto[00m in [38;5;118m~/CS353/Lab7[00m on [38;5;81mmaster[38;5;166m ●[38;5;161m ●[00m[38;5;166m λ[00m [K[?1h=[?2004h[1m[31mu[0m[39m[1m[31mu[0m[39m[90mname -a[39m[1m[31mu[1m[31mn[0m[39m[90mn[90ma[90mm[90me[90m [90m-[90ma[39m[1m[31mu[1m[31mn[1m[31ma[0m[39m[39m [39m [39m [39m [39m [39m [90mme -a[39m[0m[32mu[0m[32mn[0m[32ma[32mm[32me[39m[39m [39m-[39ma[?1l>[?2004l
]2;uname -a]1;unameLinux DESKTOP-KR0Q71I 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
[1m[7m%[27m[1m[0m                                                                                                                                    ]2;ssusanto@DESKTOP-KR0Q71I:~/CS353/Lab7]1;~/CS353/Lab7[0m[27m[24m[J[38;5;135mssusanto[00m in [38;5;118m~/CS353/Lab7[00m on [38;5;81mmaster[38;5;166m ●[38;5;161m ●[00m[38;5;166m λ[00m [K[?1h=[?2004h[1m[31mc[0m[39m[1m[31mc[1m[31ma[0m[39m[0m[32mc[0m[32ma[32mt[39m[90m lab7c.logfile[39m[14D[39m [39m[4m/[24m[39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [12D[90metc/os-release[39m[14D[4m/[39m[4me[39m[4mt[39m[4mc[39m[4m/[39m[4mo[39m[4ms[39m[4m-[39m[4mr[39m[4me[39m[4ml[39m[4me[39m[4ma[39m[4ms[39m[4me[24m[?1l>[?2004l
]2;cat /etc/os-release]1;catNAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
[1m[7m%[27m[1m[0m                                                                                                                                    ]2;ssusanto@DESKTOP-KR0Q71I:~/CS353/Lab7]1;~/CS353/Lab7[0m[27m[24m[J[38;5;135mssusanto[00m in [38;5;118m~/CS353/Lab7[00m on [38;5;81mmaster[38;5;166m ●[38;5;161m ●[00m[38;5;166m λ[00m [K[?1h=[?2004h[1m[31mm[0m[39m[1m[31mm[1m[31ma[0m[39m[0m[39mm[0m[39mak[32mm[32ma[32mk[32me[39m[90m lab7c && ./lab7c 12345 lab7c.logfile[39m[37D[39m [39mc[39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [35D[90mlean[39m[39ml[39me[39ma[39mn[?1l>[?2004l
]2;make clean]1;makerm -f a.out x y
[1m[7m%[27m[1m[0m                                                                                                                                    ]2;ssusanto@DESKTOP-KR0Q71I:~/CS353/Lab7]1;~/CS353/Lab7[0m[27m[24m[J[38;5;135mssusanto[00m in [38;5;118m~/CS353/Lab7[00m on [38;5;81mmaster[38;5;166m ●[38;5;161m ●[00m[38;5;166m λ[00m [K[?1h=[?2004h[1m[31mm[0m[39m[1m[31mm[1m[31ma[0m[39m[1m[31mm[1m[31ma[1m[31mk[0m[39m[0m[32mm[0m[32ma[0m[32mk[32me[39m[90m clean[39m[39m [39m[4ml[24m[39m [39m [39m [39m [90mab7c && ./lab7c 12345 lab7c.logfile[39m[35D[4ml[39m[4ma[24m[4ma[39m[4mb[24m[4mb[39m[4m7[24m[4m7[39m[4mc[24m[39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [39m [31D[?1l>[?2004l
]2;make lab7c]1;makeg++ -g -Wall -std=c++11 -DLOCALHOST=\"127.0.0.1\" -o lab7c lab7c.cpp my_socket.cpp my_readwrite.cpp my_timestamp.cpp my_connection.cpp -lcrypto -pthread
[1m[7m%[27m[1m[0m                                                                                                                                    ]2;ssusanto@DESKTOP-KR0Q71I:~/CS353/Lab7]1;~/CS353/Lab7[0m[27m[24m[J[38;5;135mssusanto[00m in [38;5;118m~/CS353/Lab7[00m on [38;5;81mmaster[38;5;166m ●[38;5;161m ●[00m[38;5;166m λ[00m [K[?1h=[?2004h[32m.[39m[32m.[39m[90m/lab7c 12345 lab7c.logfile[39m[26D[4m[32m.[4m[32m/[24m[39m[24m[32m.[24m[32m/[32ml[32ma[32mb[32m7[32mc[39m[39m [39m1[39m2[39m3[39m4[39m5[39m [39m[4ml[39m[4ma[39m[4mb[39m[4m7[39m[4mc[39m[4m.[39m[4ml[39m[4mo[39m[4mg[39m[4mf[39m[4mi[39m[4ml[39m[4me[24m[?1l>[?2004l
]2;./lab7c 12345 lab7c.logfile]1;./lab7c> status
The following connections are active:
1
2
> quit
Cannot quit, the following connections are active:
1
2
> help
Available commands are:
	help
	status
	quit
> lajshdasj
Available commands are:
	help
	status
	quit
> help
Available commands are:
	help
	status
	quit
> status
The following connections are active:
1
2
> status
The following connections are active:
2
> status
The following connections are active:
2
> quit
Cannot quit, the following connections are active:
2
> status
No active connections
> quit
[1m[7m%[27m[1m[0m                                                                                                                                    ]2;ssusanto@DESKTOP-KR0Q71I:~/CS353/Lab7]1;~/CS353/Lab7[0m[27m[24m[J[38;5;135mssusanto[00m in [38;5;118m~/CS353/Lab7[00m on [38;5;81mmaster[38;5;166m ●[38;5;161m ●[00m[38;5;166m λ[00m [K[?1h=[?2004h[1m[31me[0m[39m[1m[31me[0m[39m[90mxit[39m[0m[32me[32mx[39m[1m[31me[1m[31mx[1m[31mi[0m[39m[90mi[90mt[39m[0m[32me[0m[32mx[0m[32mi[32mt[39m[39m [?1l>[?2004l
]2;exit]1;exit
Script done on 2023-02-27 18:11:57-08:00 [COMMAND_EXIT_CODE="0"]
